---
# ========================
# File tasks/main.yml
#
# ========================

- name: Check if selinux is enabled
  include: selinux.yml

- name: Check if firewall is enabled
  include: firewall.yml

- name: APT | Install xrdp
  become: true
  become_user: root
  apt:
    update_cache: true
    name: "xrdp"
    state: latest
  when: ansible_os_family == 'Debian'

- name: YUM | Ensure xrdp is installed and up-to-date on RHEL 7
  become: true
  become_user: root
  yum:
    name: 
      - xrdp
      - xorgxrdp
    state: present
    update_cache: true
  vars:
    ansible_python_interpreter: /usr/bin/python
  when:
    - "ansible_distribution_major_version | int <= 7"
    - "ansible_os_family == 'RedHat'"
    
- name: YUM | Ensure xrdp is installed and up-to-date on RHEL 8
  become: true
  become_user: root
  yum:
    name: 
      - xrdp
      - xorgxrdp
    state: present
    update_cache: true
  when:
    - "ansible_distribution_major_version | int > 7"
    - "ansible_os_family == 'RedHat'"

- name: PLAY | Enable Xorg
  become: true
  become_user: root
  blockinfile:
    path: /etc/xrdp/xrdp.ini
    insertbefore: '\[Xvnc\]'
    marker: " "
    block: |
      [Xorg]
      name=Xorg
      lib=libxup.so
      username=ask
      password=ask
      ip=127.0.0.1
      port=-1
      code=20

- name: SYSTEMD | Start and enable xrdp
  become: true
  become_user: root
  systemd:
    name: xrdp
    state: started
    enabled: true

- name: FIREWALLD | Ensure Port 3389 enabled in firewall on 7
  become: true
  become_user: root
  firewalld:
    port: 3389/tcp
    permanent: true
    state: enabled
    immediate: true
  vars:
    ansible_python_interpreter: /usr/bin/python
  when: 
    - firewalld_enabled
    - "ansible_distribution_major_version | int <= 7"

- name: FIREWALLD | Ensure Port 3389 enabled in firewall on 8
  become: true
  become_user: root
  firewalld:
    port: 3389/tcp
    permanent: true
    state: enabled
    immediate: true
  when: 
    - firewalld_enabled
    - "ansible_distribution_major_version | int > 7"

- name: COMMAND | Configure SELinux context
  become: true
  become_user: root
  command: "{{ item }}"
  with_items:
    - chcon --type=bin_t /usr/sbin/xrdp
    - chcon --type=bin_t /usr/sbin/xrdp-sesman
  when: selinux_enabled